"""Deterministic, evaluation-only scenarios for rare operational failures.

Inputs are structured facts, never generated CCTV evidence. Expected results
describe review/alert policy and cannot be persisted as production labels.
"""

SCENARIOS = [
    {"id": "junction-mannequin-survives-worker-restart", "domain": "detection_quality",
     "severity": "critical", "kind": "intrusion_incident", "action_key": "alert",
     "inputs": {"motion_history": False, "static_warmup_complete": False,
                "incident_fingerprint_active": True, "worker_restarted": True},
     "expected": {"alert": False, "duplicate_suppressed": True}},
    {"id": "real-person-first-entry-alerts-once", "domain": "detection_quality",
     "severity": "critical", "kind": "intrusion_incident", "action_key": "alert",
     "inputs": {"motion_history": True, "static_warmup_complete": False,
                "incident_fingerprint_active": False, "worker_restarted": False},
     "expected": {"alert": True, "duplicate_suppressed": False}},
    {"id": "five-moving-passersby-not-a-crowd", "domain": "crowd_quality",
     "severity": "high", "kind": "crowd_policy", "action_key": "alert",
     "inputs": {"people": 5, "stationary_seconds": 0, "staff_zone_overlap": False},
     "expected": {"alert": False, "staff_area_priority": False}},
    {"id": "six-people-under-five-minutes-not-a-crowd", "domain": "crowd_quality",
     "severity": "high", "kind": "crowd_policy", "action_key": "alert",
     "inputs": {"people": 6, "stationary_seconds": 299, "staff_zone_overlap": False},
     "expected": {"alert": False, "staff_area_priority": False}},
    {"id": "six-stationary-for-five-minutes-is-one-crowd", "domain": "crowd_quality",
     "severity": "high", "kind": "crowd_policy", "action_key": "alert",
     "inputs": {"people": 6, "stationary_seconds": 300, "staff_zone_overlap": False},
     "expected": {"alert": True, "staff_area_priority": False}},
    {"id": "staff-area-intrusion-outranks-generic-crowd", "domain": "crowd_quality",
     "severity": "critical", "kind": "crowd_policy", "action_key": "alert",
     "inputs": {"people": 6, "stationary_seconds": 300, "staff_zone_overlap": True},
     "expected": {"alert": False, "staff_area_priority": True}},
    {"id": "quarantine-retains-evidence-without-notifying-or-learning",
     "domain": "alert_quality", "severity": "critical", "kind": "quality_policy",
     "action_key": "review_only",
     "inputs": {"mode": "quarantined", "detected": True},
     "expected": {"alert_recorded": True, "evidence_retained": True,
                  "notification_sent": False, "training_eligible": False,
                  "review_only": True}},
    {"id": "static-chair-no-alert", "domain": "detection_quality", "severity": "high",
     "kind": "person_motion", "action_key": "alert",
     "inputs": {"moving": False, "motion_history": False}, "expected": {"alert": False}},
    {"id": "person-walks-then-pauses", "domain": "detection_quality", "severity": "high",
     "kind": "person_motion", "action_key": "alert",
     "inputs": {"moving": False, "motion_history": True}, "expected": {"alert": True}},
    {"id": "same-track-repeat-within-rearm-is-suppressed",
     "domain": "detection_quality", "severity": "critical",
     "kind": "track_rearm", "action_key": "alert",
     "inputs": {"same_track": True, "elapsed_seconds": 45,
                "rearm_seconds": 120},
     "expected": {"alert": False, "duplicate_suppressed": True,
                  "rearmed": False}},
    {"id": "same-track-after-rearm-can-alert-again",
     "domain": "detection_quality", "severity": "high",
     "kind": "track_rearm", "action_key": "alert",
     "inputs": {"same_track": True, "elapsed_seconds": 121,
                "rearm_seconds": 120},
     "expected": {"alert": True, "duplicate_suppressed": False,
                  "rearmed": True}},
    {"id": "new-track-is-not-suppressed-by-prior-person",
     "domain": "detection_quality", "severity": "critical",
     "kind": "track_rearm", "action_key": "alert",
     "inputs": {"same_track": False, "elapsed_seconds": 10,
                "rearm_seconds": 120},
     "expected": {"alert": True, "duplicate_suppressed": False,
                  "rearmed": True}},
    {"id": "public-passage-exclusion-never-intrudes",
     "domain": "zone_quality", "severity": "critical",
     "kind": "protected_zone", "action_key": "alert",
     "inputs": {"inside_protected_zone": False,
                "inside_excluded_public_area": True,
                "dwell_seconds": 600, "minimum_dwell_seconds": 5},
     "expected": {"alert": False, "excluded_as_public": True,
                  "dwell_satisfied": True}},
    {"id": "protected-zone-transient-does-not-alert",
     "domain": "zone_quality", "severity": "high",
     "kind": "protected_zone", "action_key": "alert",
     "inputs": {"inside_protected_zone": True,
                "inside_excluded_public_area": False,
                "dwell_seconds": 2, "minimum_dwell_seconds": 5},
     "expected": {"alert": False, "excluded_as_public": False,
                  "dwell_satisfied": False}},
    {"id": "protected-zone-sustained-entry-alerts",
     "domain": "zone_quality", "severity": "critical",
     "kind": "protected_zone", "action_key": "alert",
     "inputs": {"inside_protected_zone": True,
                "inside_excluded_public_area": False,
                "dwell_seconds": 6, "minimum_dwell_seconds": 5},
     "expected": {"alert": True, "excluded_as_public": False,
                  "dwell_satisfied": True}},
    {"id": "camera-handoff-global-id-preserved", "domain": "identity_handoff", "severity": "medium",
     "kind": "camera_handoff", "action_key": "review",
     "inputs": {"expected_same_person": True, "source_global_id": "p-42",
                "target_global_id": "p-42", "gap_seconds": 4, "max_gap_seconds": 15},
     "expected": {"identity_preserved": True, "id_loss": False, "review": False}},
    {"id": "camera-handoff-id-lost", "domain": "identity_handoff", "severity": "high",
     "kind": "camera_handoff", "action_key": "review",
     "inputs": {"expected_same_person": True, "source_global_id": "p-42",
                "target_global_id": None, "gap_seconds": 5, "max_gap_seconds": 15},
     "expected": {"identity_preserved": False, "id_loss": True, "review": True,
                  "unique_count_confident": False}},
    {"id": "camera-handoff-too-late", "domain": "identity_handoff", "severity": "medium",
     "kind": "camera_handoff", "action_key": "review",
     "inputs": {"expected_same_person": True, "source_global_id": "p-42",
                "target_global_id": "p-42", "gap_seconds": 45, "max_gap_seconds": 15},
     "expected": {"identity_preserved": False, "review": True}},
    {"id": "critical-zone-camera-loss", "domain": "coverage", "severity": "critical",
     "kind": "coverage", "inputs": {"required": 1, "fresh": 0, "clip": False},
     "expected": {"status": "critical"}},
    {"id": "critical-zone-no-clip", "domain": "coverage", "severity": "high",
     "kind": "coverage", "inputs": {"required": 1, "fresh": 1, "clip": False},
     "expected": {"status": "warning"}},
    {"id": "clip-sla-excludes-ineligible-alerts", "domain": "evidence_quality",
     "severity": "high", "kind": "clip_sla", "action_key": "breach",
     "inputs": {"eligible": 0, "available": 0, "unknown": 5,
                "minimum_rate": 0.95},
     "expected": {"availability_rate": None, "breach": False,
                  "denominator_valid": False}},
    {"id": "clip-sla-fails-on-missing-eligible-clips", "domain": "evidence_quality",
     "severity": "critical", "kind": "clip_sla", "action_key": "breach",
     "inputs": {"eligible": 20, "available": 14, "unknown": 0,
                "minimum_rate": 0.95},
     "expected": {"availability_rate": 0.7, "breach": True,
                  "denominator_valid": True}},
    {"id": "merchandise-out-matches-sale", "domain": "merchandise_flow", "severity": "medium",
     "kind": "merchandise_flow", "action_key": "review",
     "inputs": {"outbound_qty": 2, "sold_qty": 2, "transfer_qty": 0,
                "return_qty": 0, "camera_evidence": True},
     "expected": {"unmatched_qty": 0, "review": False, "accusation": False}},
    {"id": "merchandise-out-without-matching-event", "domain": "merchandise_flow", "severity": "high",
     "kind": "merchandise_flow", "action_key": "review",
     "inputs": {"outbound_qty": 4, "sold_qty": 1, "transfer_qty": 1,
                "return_qty": 0, "camera_evidence": True},
     "expected": {"unmatched_qty": 2, "review": True, "accusation": False}},
    {"id": "merchandise-flow-camera-evidence-missing", "domain": "merchandise_flow", "severity": "high",
     "kind": "merchandise_flow", "action_key": "review",
     "inputs": {"outbound_qty": 1, "sold_qty": 1, "transfer_qty": 0,
                "return_qty": 0, "camera_evidence": False},
     "expected": {"unmatched_qty": 0, "review": True,
                  "reason": "camera_evidence_unavailable", "accusation": False}},
    {"id": "zone-boundary-transient-no-alert", "domain": "zone_boundary", "severity": "high",
     "kind": "zone_boundary", "action_key": "alert",
     "inputs": {"inside_ratio": 0.55, "consecutive_frames": 2,
                "min_inside_ratio": 0.60, "min_frames": 3},
     "expected": {"alert": False, "suppressed_as_boundary": True}},
    {"id": "zone-entry-sustained-alert", "domain": "zone_boundary", "severity": "high",
     "kind": "zone_boundary", "action_key": "alert",
     "inputs": {"inside_ratio": 0.82, "consecutive_frames": 5,
                "min_inside_ratio": 0.60, "min_frames": 3},
     "expected": {"alert": True, "suppressed_as_boundary": False}},
    {"id": "offline-feed", "domain": "camera_health", "severity": "critical",
     "kind": "frame_health", "action_key": "review",
     "inputs": {"online": False, "has_frame": False, "age_seconds": 0,
                "max_age_seconds": 120},
     "expected": {"issue": "offline_feed", "review": True}},
    {"id": "stale-frame", "domain": "camera_health", "severity": "critical",
     "kind": "frame_health", "action_key": "review",
     "inputs": {"online": True, "has_frame": True, "age_seconds": 900,
                "max_age_seconds": 120},
     "expected": {"issue": "stale_frame", "review": True}},
    {"id": "fresh-feed", "domain": "camera_health", "severity": "medium",
     "kind": "frame_health", "action_key": "review",
     "inputs": {"online": True, "has_frame": True, "age_seconds": 15,
                "max_age_seconds": 120},
     "expected": {"issue": None, "review": False}},
    {"id": "critical-alert-late-and-deduplicated", "domain": "alert_pipeline", "severity": "critical",
     "kind": "alert_pipeline", "action_key": "breach",
     "inputs": {"critical": True, "latency_seconds": 150, "max_latency_seconds": 120,
                "occurrences": 20, "unique_fingerprints": 1, "acknowledged": True,
                "age_seconds": 200},
     "expected": {"latency_breach": True, "duplicate_suppressed": 19,
                  "emitted": 1, "breach": True}},
    {"id": "critical-alert-on-time", "domain": "alert_pipeline", "severity": "critical",
     "kind": "alert_pipeline", "action_key": "breach",
     "inputs": {"critical": True, "latency_seconds": 30, "max_latency_seconds": 120,
                "occurrences": 1, "unique_fingerprints": 1, "acknowledged": True,
                "age_seconds": 60},
     "expected": {"latency_breach": False, "duplicate_suppressed": 0,
                  "emitted": 1, "breach": False}},
    {"id": "critical-alert-unacknowledged", "domain": "alert_pipeline", "severity": "critical",
     "kind": "alert_sla", "action_key": "breach",
     "inputs": {"critical": True, "age_seconds": 360, "acknowledged": False},
     "expected": {"breach": True}},
    {"id": "normal-alert-within-sla", "domain": "alert_pipeline", "severity": "medium",
     "kind": "alert_sla", "action_key": "breach",
     "inputs": {"critical": False, "age_seconds": 600, "acknowledged": False},
     "expected": {"breach": False}},
    {"id": "single-person-after-close", "domain": "lone_worker", "severity": "high",
     "kind": "lone_worker", "action_key": "review",
     "inputs": {"after_hours": True, "people": 1, "tracking_reliable": True},
     "expected": {"review": True, "confidence": "supported"}},
    {"id": "single-person-unreliable-tracking", "domain": "lone_worker", "severity": "high",
     "kind": "lone_worker", "action_key": "review",
     "inputs": {"after_hours": True, "people": 1, "tracking_reliable": False},
     "expected": {"review": True, "confidence": "needs_confirmation"}},
    {"id": "two-people-after-close", "domain": "lone_worker", "severity": "medium",
     "kind": "lone_worker", "action_key": "review",
     "inputs": {"after_hours": True, "people": 2, "tracking_reliable": True},
     "expected": {"review": False}},
    {"id": "odoo-refund-correlated", "domain": "pos_correlation", "severity": "medium",
     "kind": "event_correlation", "action_key": "review",
     "inputs": {"source_event": True, "camera_evidence": True,
                "time_delta_seconds": 40, "max_delta_seconds": 300},
     "expected": {"correlated": True, "review": False, "accusation": False}},
    {"id": "odoo-no-sale-missing-cctv-correlation", "domain": "pos_correlation", "severity": "high",
     "kind": "event_correlation", "action_key": "review",
     "inputs": {"source_event": True, "camera_evidence": False,
                "time_delta_seconds": None, "max_delta_seconds": 300},
     "expected": {"correlated": False, "review": True,
                  "reason": "camera_evidence_unavailable", "accusation": False}},
    {"id": "cctv-event-missing-odoo-event", "domain": "pos_correlation", "severity": "high",
     "kind": "event_correlation", "action_key": "review",
     "inputs": {"source_event": False, "camera_evidence": True,
                "time_delta_seconds": None, "max_delta_seconds": 300},
     "expected": {"correlated": False, "review": True,
                  "reason": "source_event_unavailable", "accusation": False}},
    {"id": "pos-no-sale-after-hours", "domain": "pos_correlation", "severity": "high",
     "kind": "risk", "inputs": {"event_type": "no_sale", "amount": 75000,
                "after_hours": True, "camera_evidence": False},
     "expected": {"band": "high_review", "human_review_required": True,
                  "accusation": False}},
    {"id": "delivery-approved-window", "domain": "delivery", "severity": "medium",
     "kind": "delivery", "action_key": "review",
     "inputs": {"within_window": True, "camera_evidence": True},
     "expected": {"review": False}},
    {"id": "delivery-outside-window", "domain": "delivery", "severity": "high",
     "kind": "delivery", "action_key": "review",
     "inputs": {"within_window": False, "camera_evidence": True},
     "expected": {"review": True}},
    {"id": "ambiguous-whatsapp-yes", "domain": "human_feedback", "severity": "high",
     "kind": "feedback", "action_key": "clarification_required",
     "inputs": {"store": None, "camera": None, "occurred_at": None,
                "observed": "yes", "expected": None, "label": "yes"},
     "expected": {"clarification_required": True, "label_ready": False,
                  "training_eligible": False}},
    {"id": "ambiguous-whatsapp-probably-false", "domain": "human_feedback", "severity": "high",
     "kind": "feedback", "action_key": "clarification_required",
     "inputs": {"store": "Junction", "camera": "Channel 5",
                "occurred_at": "2026-08-21T13:40:00+03:00",
                "observed": "person behind counter", "expected": "staff only",
                "label": "probably false"},
     "expected": {"clarification_required": True, "label_ready": False,
                  "training_eligible": False}},
    {"id": "explicit-human-label-ready-for-real-review", "domain": "human_feedback", "severity": "medium",
     "kind": "feedback", "action_key": "clarification_required",
     "inputs": {"store": "Junction", "camera": "Channel 5",
                "occurred_at": "2026-08-21T13:40:00+03:00",
                "observed": "authorised cashier", "expected": "no staff-area alert",
                "label": "false_alert"},
     "expected": {"clarification_required": False, "label_ready": True,
                  "training_eligible": False}},
]
