apiVersion: v1
kind: Secret
metadata:
  name: vivoguard-secrets
  labels: { {{- include "vg.labels" (dict "Release" .Release "component" "secrets") | nindent 4 }} }
type: Opaque
stringData:
  jwt-secret:           {{ .Values.secrets.jwtSecret | quote }}
  fernet-key:           {{ .Values.secrets.fernetKey | default (randAlphaNum 44) | quote }}
  postgres-password:    {{ .Values.secrets.postgresPassword | quote }}
  s3-secret-key:        {{ .Values.secrets.s3SecretKey | quote }}
  bootstrap-admin-pw:   {{ .Values.secrets.bootstrapAdminPw | quote }}
  smtp-password:        {{ .Values.notifications.smtp.password | default "" | quote }}
  twilio-token:         {{ .Values.notifications.twilio.token | default "" | quote }}
